kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  ports:
    - name: http
      port: 80
      nodePort: 30007
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: nginx
  type: NodePort
